import {
  SiCss3,
  SiSass,
  SiCssmodules,
  SiHtml5,
  SiStyledcomponents,
  SiJavascript,
  SiTypescript,
  SiReact,
  SiReactrouter,
  SiReactquery,
  SiRedux,
  SiReduxsaga,
  SiNextdotjs,
  SiExpress,
  SiDocker,
  SiGit,
} from 'react-icons/si'

export const SKILLS_LIST = [
  { name: 'HTML', icon: SiHtml5, color: '#E44D26' },
  { name: 'CSS', icon: SiCss3, color: '#1572B6' },
  { name: 'Sass', icon: SiSass, color: '#CC6699' },
  { name: 'Styled-components', icon: SiStyledcomponents, color: '#DB7093' },
  { name: 'CSS Modules', icon: SiCssmodules, color: '#2965f1' },
  { name: 'JavaScript', icon: SiJavascript, color: '#F7DF1E' },
  { name: 'TypeScript', icon: SiTypescript, color: '#3178C6' },
  { name: 'React.js', icon: SiReact, color: '#61DAFB' },
  { name: 'React Router', icon: SiReactrouter, color: '#CA4245' },
  { name: 'React Query', icon: SiReactquery, color: '#FF4154' },
  { name: 'Custom Hooks', icon: SiReact, color: '#61DAFB' },
  { name: 'Redux', icon: SiRedux, color: '#764ABC' },
  { name: 'Redux Toolkit', icon: SiReduxsaga, color: '#764ABC' },
  { name: 'Next.js', icon: SiNextdotjs, color: '#000000' },
  { name: 'Express.js', icon: SiExpress, color: '#000000' },
  { name: 'Docker', icon: SiDocker, color: '#2496ED' },
  { name: 'Git', icon: SiGit, color: '#F05032' },
]
